from django.db import models

class Players(models.Model):
    name = models.CharField(max_length = 100)
    team = models.CharField(max_length = 20)
    position = models.CharField(max_length = 10)
    pass_yds = models.IntegerField()
    pass_tds = models.IntegerField()
    interceptions = models.IntegerField()
    fumbles = models.IntegerField()
    rush_yds = models.IntegerField()
    rush_tds = models.IntegerField()
    rec_yds = models.IntegerField()
    rec_tds = models.IntegerField()
    points = models.FloatField()

class Week1(models.Model):
    name = models.CharField(max_length = 100)
    team = models.CharField(max_length = 20)
    position = models.CharField(max_length = 10)
    pass_yds = models.FloatField()
    pass_tds = models.IntegerField()
    interceptions = models.IntegerField()
    fumbles = models.IntegerField()
    rush_yds = models.FloatField()
    rush_tds = models.IntegerField()
    rec_yds = models.FloatField()
    rec_tds = models.IntegerField()
    points = models.FloatField()

class Week2(models.Model):
    name = models.CharField(max_length = 100)
    team = models.CharField(max_length = 20)
    position = models.CharField(max_length = 10)
    pass_yds = models.FloatField()
    pass_tds = models.IntegerField()
    interceptions = models.IntegerField()
    fumbles = models.IntegerField()
    rush_yds = models.FloatField()
    rush_tds = models.IntegerField()
    rec_yds = models.FloatField()
    rec_tds = models.IntegerField()
    points = models.FloatField()

class Week3(models.Model):
    name = models.CharField(max_length = 100)
    team = models.CharField(max_length = 20)
    position = models.CharField(max_length = 10)
    pass_yds = models.FloatField()
    pass_tds = models.IntegerField()
    interceptions = models.IntegerField()
    fumbles = models.IntegerField()
    rush_yds = models.FloatField()
    rush_tds = models.IntegerField()
    rec_yds = models.FloatField()
    rec_tds = models.IntegerField()
    points = models.FloatField()

class Week4(models.Model):
    name = models.CharField(max_length = 100)
    team = models.CharField(max_length = 20)
    position = models.CharField(max_length = 10)
    pass_yds = models.FloatField()
    pass_tds = models.IntegerField()
    interceptions = models.IntegerField()
    fumbles = models.IntegerField()
    rush_yds = models.FloatField()
    rush_tds = models.IntegerField()
    rec_yds = models.FloatField()
    rec_tds = models.IntegerField()
    points = models.FloatField()

class Week5(models.Model):
    name = models.CharField(max_length = 100)
    team = models.CharField(max_length = 20)
    position = models.CharField(max_length = 10)
    pass_yds = models.FloatField()
    pass_tds = models.IntegerField()
    interceptions = models.IntegerField()
    fumbles = models.IntegerField()
    rush_yds = models.FloatField()
    rush_tds = models.IntegerField()
    rec_yds = models.FloatField()
    rec_tds = models.IntegerField()
    points = models.FloatField()