# Generated by Django 3.1.5 on 2021-01-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=10)),
                ('pass_yds', models.IntegerField()),
                ('pass_tds', models.IntegerField()),
                ('interceptions', models.IntegerField()),
                ('fumbles', models.IntegerField()),
                ('rush_yds', models.IntegerField()),
                ('rush_tds', models.IntegerField()),
                ('rec_yds', models.IntegerField()),
                ('rec_tds', models.IntegerField()),
                ('points', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Week2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=10)),
                ('pass_yds', models.IntegerField()),
                ('pass_tds', models.IntegerField()),
                ('interceptions', models.IntegerField()),
                ('fumbles', models.IntegerField()),
                ('rush_yds', models.IntegerField()),
                ('rush_tds', models.IntegerField()),
                ('rec_yds', models.IntegerField()),
                ('rec_tds', models.IntegerField()),
                ('points', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Week3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=10)),
                ('pass_yds', models.IntegerField()),
                ('pass_tds', models.IntegerField()),
                ('interceptions', models.IntegerField()),
                ('fumbles', models.IntegerField()),
                ('rush_yds', models.IntegerField()),
                ('rush_tds', models.IntegerField()),
                ('rec_yds', models.IntegerField()),
                ('rec_tds', models.IntegerField()),
                ('points', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Week4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=10)),
                ('pass_yds', models.IntegerField()),
                ('pass_tds', models.IntegerField()),
                ('interceptions', models.IntegerField()),
                ('fumbles', models.IntegerField()),
                ('rush_yds', models.IntegerField()),
                ('rush_tds', models.IntegerField()),
                ('rec_yds', models.IntegerField()),
                ('rec_tds', models.IntegerField()),
                ('points', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Week5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=10)),
                ('pass_yds', models.IntegerField()),
                ('pass_tds', models.IntegerField()),
                ('interceptions', models.IntegerField()),
                ('fumbles', models.IntegerField()),
                ('rush_yds', models.IntegerField()),
                ('rush_tds', models.IntegerField()),
                ('rec_yds', models.IntegerField()),
                ('rec_tds', models.IntegerField()),
                ('points', models.FloatField()),
            ],
        ),
    ]
