# Generated by Django 3.1.5 on 2021-01-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_week1_week2_week3_week4_week5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week1',
            name='pass_yds',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='week1',
            name='rec_yds',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='week1',
            name='rush_yds',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='week2',
            name='pass_yds',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='week2',
            name='rec_yds',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='week2',
            name='rush_yds',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='week3',
            name='pass_yds',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='week3',
            name='rec_yds',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='week3',
            name='rush_yds',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='week4',
            name='pass_yds',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='week4',
            name='rec_yds',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='week4',
            name='rush_yds',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='week5',
            name='pass_yds',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='week5',
            name='rec_yds',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='week5',
            name='rush_yds',
            field=models.FloatField(),
        ),
    ]
