# Generated by Django 3.1.5 on 2021-01-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_auto_20210126_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='points',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
