# Generated by Django 3.1.5 on 2021-01-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_players_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='rostered_by',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='players',
            name='pass_yds',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='players',
            name='rec_yds',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='players',
            name='rush_yds',
            field=models.FloatField(),
        ),
    ]
