# Generated by Django 3.1.5 on 2021-02-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_auto_20210203_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('win', models.IntegerField()),
                ('loss', models.IntegerField()),
                ('tie', models.IntegerField()),
                ('points', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
